version: '3'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: sastaticketassessmentdb
      POSTGRES_USER: maazpostgres
      POSTGRES_PASSWORD: maazpostgrespassword
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  

  web:
    build: .
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

  
networks:
  mynetwork: